WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.1.60:5000/ (Press CTRL+C to quit)
INFO:root:Main request sucessful
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\Light\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Light\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Light\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Light\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\Users\Light\Code\SUSE\EndpointStatus\app.py", line 16, in hello_world
    app.logger-logging.info("Main request sucessful")
TypeError: unsupported operand type(s) for -: 'Logger' and 'NoneType'
INFO:werkzeug:127.0.0.1 - - [01/Aug/2021 21:24:52] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [01/Aug/2021 21:24:53] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
